[package]
name = "libwing"
version = "1.0.4"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dannydulai/libwing"
edition = "2021"
description = "A library for communicationg with the Behringer Wing Digital Mixer"
documentation = "https://docs.rs/libwing"



[lib]
name = "libwing"
crate-type = ["rlib", "cdylib"]

[workspace]
resolver = "2"
members = ["native/wing"]


[dependencies]
socket2 = "0.5"
lazy_static = "1.4"
jzon = "0.12.5"
thiserror = "2.0.11"
rustler = "0.36.1"
rand = "0.8"

[dev-dependencies]
eframe = "0.26.0"
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "wingmeters"
path = "tools/wingmeters.rs"

[[example]]
name = "wingmon"
path = "tools/wingmon.rs"

[[example]]
name = "wingschema"
path = "tools/wingschema.rs"

[[example]]
name = "wingprop"
path = "tools/wingprop.rs"
